apiVersion: apps/v1
kind: Deployment
metadata:
  name: xcomsrvc
  namespace: aws-commerce
spec:
  selector:
    matchLabels:
      app: xcomsrvc
  replicas: 1
  template:
    metadata:
      labels:
        app: xcomsrvc
    spec:
      securityContext:
        runAsUser: 1000
      containers:
      - name: xcomsrvc
        image: aws-commerce/xcomsrvc:release0.1
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: development

---

apiVersion: v1
kind: Service
metadata:
  name: xcomsrvc
  namespace: aws-commerce
spec:
  selector:
    app: xcomsrvc

  ports:
    - name: http
      port: 8090